import "server-only";

import {
  CopilotRuntime,
  CopilotKitIntelligence,
  InMemoryAgentRunner,
} from "@copilotkit/runtime/v2";
import { HttpAgent } from "@ag-ui/client";

/**
 * The Intelligence runtime from the Intelligence Quickstart, built once and
 * mounted twice.
 *
 * Mounted multi-route at `/api/copilotkit-threads`, which drives the three Rich
 * Threads routes — what `threads`, `threads-lifecycle`, `headless-threads` and
 * the drawer page publish.
 *
 * A factory rather than a shared instance, so a mount's channel activation
 * stays its own.
 *
 * The three credentials below come from `frontend/.env.local`, copied from the
 * project `copilotkit init` scaffolded under `1cli-testing/`. Nothing here logs
 * in: `COPILOTKIT_LICENSE_TOKEN` is an EdDSA-signed JWT that
 * `@copilotkit/license-verifier` checks offline against a bundled public key.
 * `CPK_INTELLIGENCE_API_KEY` is the project key for the managed thread store, so
 * threads written here land in the same project as the CLI app.
 */

const AGENT_URL = process.env.MS_AGENT_URL ?? "http://localhost:8000";

// Treat empty/whitespace values as absent. An empty `KEY=` line in an env file
// still *defines* the variable — so a plain `??` or truthiness check on
// process.env would sail past it and hand Intelligence an empty credential.
const firstSet = (...values: (string | undefined)[]) =>
  values.find((v) => typeof v === "string" && v.trim().length > 0)?.trim();

// `CPK_INTELLIGENCE_API_KEY` is the name the docs now publish, so it is read
// first. `INTELLIGENCE_API_KEY` is what older CLIs wrote and stays accepted —
// the docs renamed the variable without saying the old one stopped working.
const INTELLIGENCE_KEY = firstSet(
  process.env.CPK_INTELLIGENCE_API_KEY,
  process.env.INTELLIGENCE_API_KEY,
);
const LICENSE_TOKEN = firstSet(process.env.COPILOTKIT_LICENSE_TOKEN);

/**
 * True when Intelligence is actually wired.
 *
 * Keyed on the project API key alone as of the 2026-09-15 sync: the Threads
 * Drawer page now states managed project setup does **not** issue
 * `COPILOTKIT_LICENSE_TOKEN`, and that the token is only for offline or
 * self-hosted licensing rather than a replacement for the managed key. The old
 * `KEY && TOKEN` gate dropped a correctly-configured managed project to the
 * in-memory runner, which is precisely the locked drawer the page says should
 * not happen.
 */
export const INTELLIGENCE_CONFIGURED = Boolean(INTELLIGENCE_KEY);

const mainAgent = () => new HttpAgent({ url: `${AGENT_URL}/` });

export function createIntelligenceRuntime(): CopilotRuntime {
  return new CopilotRuntime({
    // `default` is registered because `<CopilotThreadsDrawer>` and `useThreads`
    // fall back to DEFAULT_AGENT_ID ("default") when no agentId is given, and
    // threads are stored per agent id. `my_agent` mirrors the main runtime so
    // the same prompts work on both.
    agents: {
      default: mainAgent(),
      my_agent: mainAgent(),
      sample_agent: new HttpAgent({ url: `${AGENT_URL}/sample_agent` }),
      search_agent: new HttpAgent({ url: `${AGENT_URL}/search_agent` }),
    },

    // Without a license token the runtime still answers the read-only thread
    // routes off the in-memory runner's local-dev fallback (list, messages,
    // events, state). Rename/archive/delete and realtime sync return 422, and
    // `/info` omits `licenseStatus`, which leaves the prebuilt drawer locked.
    ...(INTELLIGENCE_KEY
      ? {
          intelligence: new CopilotKitIntelligence({
            apiKey: INTELLIGENCE_KEY,
            ...(process.env.INTELLIGENCE_API_URL
              ? { apiUrl: process.env.INTELLIGENCE_API_URL }
              : {}),
            ...(process.env.INTELLIGENCE_GATEWAY_WS_URL
              ? { wsUrl: process.env.INTELLIGENCE_GATEWAY_WS_URL }
              : {}),
          }),
          // Thread names are auto-generated by the LLM after the first message.
          // Spelled out rather than left to the default so the flag is visible
          // next to the docs' `generateThreadNames: false`.
          // [1] headless-threads: runtime options
          // [!code highlight]
          generateThreadNames: true,

          // Lock options from the same doc step, left at their defaults:
          // lockTtlSeconds: 20,               // max 3600
          // lockHeartbeatIntervalSeconds: 15, // max 3000
          // lockKeyPrefix: "cpk-ms-agent",    // when apps share one Redis

          // Threads are stored per user, so the runtime has to name one. The
          // doc calls a static value demo-only, and that is exactly what this
          // is: a fixed id keeps one shared list across browsers for manual QA.
          // Send `x-copilotkit-user-id` to check that two users get two
          // separate lists.
          // [2] threads-lifecycle: scope threads to the signed-in user
          // [3] intelligence quickstart: identifyUser
          // [!code highlight]
          identifyUser: (request: Request) => {
            const id =
              request.headers.get("x-copilotkit-user-id") ?? "demo-user";
            return { id, name: id === "demo-user" ? "Demo User" : id };
          },
          // Self-hosted / OSS licensing only. The page documents the option as
          // winning over `COPILOTKIT_LICENSE_TOKEN` when both are set; here the
          // option *is* the env var, and it is omitted when unset so a managed
          // project is not handed an empty credential.
          ...(LICENSE_TOKEN ? { licenseToken: LICENSE_TOKEN } : {}),
        }
      : { runner: new InMemoryAgentRunner() }),
  });
}
